### ISSUE TITLE
Make the server browser cool

### ISSUE THREAD

**Issue by sornas** [FredTheDino/PuckNet#103]
- [x] Handle server disconnects (#116)
- [ ] Print name and IP
- [x] Number of players (#106)
- [x] Input server name (full text input) when starting server (#105)
- [x] Handle ESCaping to the main menu (#112)
