### ISSUE TITLE
Menu!!

### ISSUE THREAD

**Issue by EMattfolk** [FredTheDino/PuckNet#34]
Stuff: 
- [x] Basic list of menu items (#83)
- [x] Title (#122)
- [x] #117
- [x] #118
- [x] #119
- [x] Cool background (#122)

Items:
- [x] "Browse servers" (#103)
- [x] "Practice" (low priority) (#83)
- [x] "Settings" (#120)
- [x] "Host server"  (#83)
- [x] "Credits" (#124)
- [x] "Quit"  (#83, removed in #112, #122)

**Comment by th3tard1sparadox** [comment]
Assets needed? (Icon on the way)

**Comment by sornas** [comment]
Background and icon I think is enough. Maybe if we want something fun for the credits?

**Comment by sornas** [comment]
~~Waiting for #89~~

**Comment by sornas** [comment]
:tada:
